version: 2

jobs:
  "environmentSetup":
   working_directory: ~/tmp
   docker:
    - image: circleci/node:6.11.3
   steps:
    - checkout
    - restore_cache:
     keys:
     - v1-dependencies-{{ checksum "package.json" }}
     # fallback to using the latest cache if no exact match is found
     - v1-dependencies-
    - run : npm install
    - run : echo "NPM installed successfully"
   
workflows:
 version: 2
 build:  
  jobs:
   - "environmentSetup"
