version: 2

jobs:
  "environmentSetup":
   working_directory: ~/tmp
   docker:
    - image: circleci/node:4.8.2
   steps:
    - checkout
    - run : npm install
    - run : npm tests
    - run : echo "NPM installed successfully"
   
workflows:
 version: 2
 build:  
  jobs:
   - "environmentSetup"
